# Generated by Django 5.1.1 on 2025-10-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. DevOps Engineer', max_length=160)),
                ('skills', models.TextField(blank=True, help_text='Enter 2–5 lines describing skills/expertise. Use line breaks.')),
                ('quote', models.CharField(blank=True, help_text='Short one-liner shown in the card', max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
