from django.contrib import admin
from .models import Category, Product, ProductImage, ProductAttachment


class ProductImageInline(admin.TabularInline):
    model = ProductImage
    extra = 1


class ProductAttachmentInline(admin.TabularInline):
    model = ProductAttachment
    extra = 0
    fields = ("title", "file",)
    verbose_name = "Attachment"
    verbose_name_plural = "Attachments"


@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    """
    Single ProductAdmin: combines Images + Attachments inlines.
    Slug is generated by the model and shown read-only under System.
    """
    list_display = (
        "name", "sku", "category", "price", "stock",
        "is_active", "is_featured", "created_at",
    )
    list_display_links = ("name", "sku")
    list_filter = ("category", "is_active", "is_featured", "created_at")
    search_fields = ("name", "sku")

    inlines = [ProductImageInline, ProductAttachmentInline]

    readonly_fields = ("slug",)

    fieldsets = (
        ("Product", {
            "fields": (
                "name",
                "sku",
                "category",
                "description",
                ("price", "stock"),
                ("is_active", "is_featured"),
            )
        }),
        ("System", {
            "classes": ("collapse",),
            "fields": ("slug",),
        }),
    )


@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    prepopulated_fields = {"slug": ("name",)}
    search_fields = ("name",)
