# Generated by Django 5.1.1 on 2025-11-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_rename_body_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste any YouTube link (watch, youtu.be, shorts, embed)', verbose_name='YouTube URL'),
        ),
    ]
