# Generated by Django 5.1.1 on 2025-11-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_embed_url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_id',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste any YouTube link (watch, youtu.be, shorts).'),
        ),
    ]
