# Generated by Django 5.1.1 on 2025-11-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_youtube_embed_url_post_youtube_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_embed_player',
            field=models.BooleanField(default=False, help_text='If ON, tries to embed the player. If the video blocks embedding, turn this OFF to show a clickable thumbnail.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste any YouTube link (watch / youtu.be / shorts).'),
        ),
    ]
