# Generated by Django 5.1.1 on 2025-11-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_show_embed_player_alter_post_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='show_embed_player',
            field=models.BooleanField(default=False, help_text='If ON, try to show the embedded YouTube player. If OFF, show a clickable thumbnail.'),
        ),
    ]
