# Generated by Django 5.1.1 on 2025-11-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_author_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for this blog post.', null=True, upload_to='blog/'),
        ),
    ]
