# Generated by Django 5.1.1 on 2025-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Leave empty to auto-generate (e.g. CAT-000123).', max_length=64, unique=True),
        ),
    ]
